# Generated by Django 5.2.1 on 2025-05-15 17:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CRU', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='featureimage',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='feature_images/'),
        ),
        migrations.AlterField(
            model_name='featureimage',
            name='article',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feature_images', to='CRU.article'),
        ),
        migrations.AlterField(
            model_name='featureimage',
            name='image_url',
            field=models.URLField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='featureimage',
            name='photo_journalist',
            field=models.CharField(max_length=255),
        ),
    ]
